-- ./SchemaManager/imports/TierSpells.sql

INSERT INTO spells (
    name, description, spell_tier, is_super_tier, mp_cost, casting_time, range, area_of_effect,
    damage_base, damage_scaling, healing_base, healing_scaling, status_effects, duration,
    created_at, updated_at
) VALUES

-- Tier 0 (5-15 MP)
('Lifestyle Magic', 'Warms up food', 0, FALSE, 5, 1, 5, NULL, 0, NULL, 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create Basic Water', 'Basic drinkable water', 0, FALSE, 10, 1, 5, NULL, 0, NULL, 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create Basic Paper', 'Creates rough paper', 0, FALSE, 10, 1, 5, NULL, 0, NULL, 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 1 (15-50 MP)
('Anti-Evil Protection', 'Reduced damage from beings with low karma value', 1, FALSE, 25, 1, 0, NULL, 0, NULL, 0, NULL, 'evil_resist', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bunny Tail', 'Reduces aggression', 1, FALSE, 20, 1, 0, NULL, 0, NULL, 0, NULL, 'aggro_down', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Camouflage', 'The Target''s skin changes color to blend into the environment', 1, FALSE, 30, 1, 0, NULL, 0, NULL, 0, NULL, 'stealth_up', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Clean', 'Removes dirt and grime', 1, FALSE, 15, 1, 30, 10, 0, NULL, 0, NULL, 'cleanse', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Compass', 'A single target will always know the direction of true north', 1, FALSE, 15, 1, 0, NULL, 0, NULL, 0, NULL, 'direction', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create Water', 'Creates sweet water', 1, FALSE, 20, 1, 30, NULL, 0, NULL, 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Destruction Water', 'Removes water, does little damage to living beings, massive damage to water elementals', 1, FALSE, 25, 1, 30, NULL, 15, 'level*1.5', 0, NULL, 'dehydrate', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Floating Board', 'Creates floating platform which changes based on caster ability', 1, FALSE, 20, 1, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lesser Mind Protection', 'Increase resistance against mind control', 1, FALSE, 25, 1, 0, NULL, 0, NULL, 0, NULL, 'mind_resist', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Light Healing', 'Minor healing', 1, FALSE, 30, 1, 5, NULL, 0, NULL, 15, 'level*2', NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Magic Arrow', 'Guaranteed-hit arrow', 1, FALSE, 25, 1, 120, NULL, 20, 'level*2', 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Odorless', 'Removes scent from caster', 1, FALSE, 20, 1, 0, NULL, 0, NULL, 0, NULL, 'scentless', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quick March', 'Increase target''s movement speed by 20%', 1, FALSE, 25, 1, 5, NULL, 0, NULL, 0, NULL, 'speed_up', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rabbit Ears', 'Improve the caster''s ability to hear', 1, FALSE, 20, 1, 0, NULL, 0, NULL, 0, NULL, 'hearing_up', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rabbit Foot', 'Improve the caster''s luck', 1, FALSE, 25, 1, 0, NULL, 0, NULL, 0, NULL, 'luck_up', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Repair', 'Repairs items, diminishing its quality', 1, FALSE, 30, 1, 5, NULL, 0, NULL, 0, NULL, 'repair', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sleep', 'Compel a target to want to sleep', 1, FALSE, 30, 1, 30, NULL, 0, NULL, 0, NULL, 'sleep', '1 minute', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 1st', 'Summon a tier 1 monster', 1, FALSE, 45, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 1st', 'Summon a tier 1 angel', 1, FALSE, 45, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Undead 1st', 'Summon a tier 1 demon', 1, FALSE, 45, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 2 (50-100 MP)
('Acid Arrow', 'Caustic projectile', 2, FALSE, 60, 1, 90, NULL, 40, 'level*3', 0, NULL, 'acid_dot', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cure Disease', 'Removes non-curse disease', 2, FALSE, 75, 2, 5, NULL, 0, NULL, 0, NULL, 'cure_disease', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hawk Eye', 'See into the distance', 2, FALSE, 50, 1, 0, NULL, 0, NULL, 0, NULL, 'vision_up', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Invisibility', 'Basic invisibility', 2, FALSE, 80, 1, 5, NULL, 0, NULL, 0, NULL, 'invisible', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lesser Dexterity', 'Dexterity boost', 2, FALSE, 60, 1, 5, NULL, 0, NULL, 0, NULL, 'dex_up', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lesser Strength', 'Strength boost', 2, FALSE, 60, 1, 5, NULL, 0, NULL, 0, NULL, 'str_up', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mass Compass', 'The entire party will always know the direction of true north ', 2, FALSE, 70, 1, 60, NULL, 0, NULL, 0, NULL, 'direction', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Message', 'Communicate with a known individual regardless of range', 2, FALSE, 50, 1, 5280, NULL, 0, NULL, 0, NULL, NULL, '1 minute', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Protection Energy Negative', 'Negative energy defense', 2, FALSE, 75, 1, 0, NULL, 0, NULL, 0, NULL, 'neg_resist', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shock Wave', 'A wave of bludgeoning and sound damage', 2, FALSE, 65, 1, 30, NULL, 45, 'level*3', 0, NULL, 'knockback', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Silence', 'Eliminates all sound in an area', 2, FALSE, 70, 1, 60, 20, 0, NULL, 0, NULL, 'silence', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 2nd', 'Single tier 2 beast Guardian summon, or multiple tier 1 beasts', 2, FALSE, 90, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 2nd', 'Single tier 2 angel Guardian summon, or multiple tier 1 angels', 2, FALSE, 90, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Undead 2nd', 'Single tier 2 undead Guardian summon, or multiple tier 1 undead', 2, FALSE, 90, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Temperature Change', 'Alters water or room temperature', 2, FALSE, 55, 1, 30, 10, 0, NULL, 0, NULL, 'temperature', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Thunderlance', 'Fire a lance like bolt that deals lightning damage', 2, FALSE, 65, 1, 60, NULL, 50, 'level*3', 0, NULL, 'shocked', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 3 (100-150 MP)
('Animate Dead', 'Convert a corpse into a low tier undead for the corpse type', 3, FALSE, 120, 2, 30, NULL, 0, NULL, 0, NULL, NULL, 'permanent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create Undead', 'Create a singe tier 3 undead, larger list than summon undead', 3, FALSE, 120, 2, 30, NULL, 0, NULL, 0, NULL, NULL, 'permanent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dimensional Move', 'Short teleport for the caster', 3, FALSE, 100, 1, 60, NULL, 0, NULL, 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Electrosphere', 'An orb of lightning which deals aoe damage, aoe range increases with caster stats', 3, FALSE, 110, 1, 90, 15, 70, 'level*4', 0, NULL, 'shocked', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fireball', 'A ball of fire that explodes and deals additional aoe damage on impact', 3, FALSE, 120, 1, 150, 20, 75, 'level*4', 0, NULL, 'burning', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Flame Resistance', 'Fire defense', 3, FALSE, 100, 1, 5, NULL, 0, NULL, 0, NULL, 'fire_resist', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fly', 'Grants flight', 3, FALSE, 100, 1, 5, NULL, 0, NULL, 0, NULL, 'flying', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Haste', 'Increase target''s speed by 30%', 3, FALSE, 110, 1, 5, NULL, 0, NULL, 0, NULL, 'hasted', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Heavy Recover', 'Strong healing', 3, FALSE, 130, 1, 5, NULL, 0, NULL, 50, 'level*4', NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Holy Light', 'Holy damage, maximum damage increases with target''s negative karma', 3, FALSE, 120, 1, 60, NULL, 80, 'level*4', 0, NULL, 'holy_damage', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hot Spring', 'Creates a temporary hot spring', 3, FALSE, 120, 2, 30, 15, 0, NULL, 0, NULL, 'hot_spring', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Iceball', 'A ball of ice that explodes and deals additional aoe damage on impact', 3, FALSE, 120, 1, 150, 20, 75, 'level*4', 0, NULL, 'frozen', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lightning', 'Piercing electrical attack with greater chance to crit targets covered in conductive armor', 3, FALSE, 110, 1, 100, NULL, 70, 'level*4', 0, NULL, 'shocked', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lopsided Duel', 'Teleport with target when target teleports away', 3, FALSE, 130, 1, 30, NULL, 0, NULL, 0, NULL, 'teleport_bind', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Slow', 'Reduces target speed by 15%', 3, FALSE, 110, 1, 60, NULL, 0, NULL, 0, NULL, 'slowed', '1 minute', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Spider Talisman', 'Summon Monster 3rd, only for talisman magic school and only summons spiders', 3, FALSE, 140, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 3rd', 'Single tier 3 angel Guardian summon, or multiple tier 2 angels', 3, FALSE, 140, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 3rd', 'Single tier 3 beast Guardian summon, or multiple tier 2 beast', 3, FALSE, 140, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Undead 3rd', 'Single tier 3 undead Guardian summon, or multiple tier 2 undead', 3, FALSE, 140, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sunlight', 'Blinds targets and damages undead', 3, FALSE, 120, 1, 90, 20, 80, 'level*4', 0, NULL, 'blinded', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Thunderball', 'Damage on hit, also creates a DOT field on terrain on impact', 3, FALSE, 120, 1, 90, 20, 75, 'level*4', 0, NULL, 'shocked', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 4 (150-200 MP)
('Burn Lance', 'Fire pierce', 4, FALSE, 160, 1, 90, NULL, 100, 'level*5', 0, NULL, 'burning', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Charm Species', 'Target considers caster to be a friend', 4, FALSE, 180, 2, 30, NULL, 0, NULL, 0, NULL, 'charmed', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Control Cloud', 'User can manipulate the clouds', 4, FALSE, 150, 2, 5280, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Crystal Lance', 'Deals Cold damage', 4, FALSE, 160, 1, 120, NULL, 110, 'level*5', 0, NULL, 'bleeding', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dehydration', 'Great damage to living beings excluding water elementals, and creatures greatly aligned with water', 4, FALSE, 170, 2, 60, NULL, 120, 'level*5', 0, NULL, 'dehydrated', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Freeze Lance', 'Ice pierce', 4, FALSE, 160, 1, 90, NULL, 100, 'level*5', 0, NULL, 'frozen', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Grand Fireball', 'Enhanced fireball', 4, FALSE, 180, 2, 180, 30, 130, 'level*5', 0, NULL, 'burning', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Holy Aura', 'An aura that damages evil characters', 4, FALSE, 180, 2, 0, NULL, 0, NULL, 0, NULL, 'holy_aura', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Holy Ray', 'Holy beam', 4, FALSE, 170, 1, 90, NULL, 120, 'level*5', 0, NULL, 'holy_damage', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shock Lance', 'Lightning pierce', 4, FALSE, 160, 1, 90, NULL, 100, 'level*5', 0, NULL, 'shocked', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Silver Lance', 'Silver element pierce', 4, FALSE, 160, 1, 90, NULL, 110, 'level*5', 0, NULL, 'silver_weak', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 4th', 'Single tier 4 angel Guardian summon, or multiple tier 3 angels', 4, FALSE, 190, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 4th', 'Single tier 4 beasts Guardian summon, or multiple tier 3 beasts', 4, FALSE, 190, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
('Summon Undead 4th', 'Single tier 4 undead Guardian summon, or multiple tier 3 undead', 4, FALSE, 190, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
('Tremor Sense', 'Ground movement detection', 4, FALSE, 150, 1, 0, NULL, 0, NULL, 0, NULL, 'tremorsense', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 5 (200-300 MP) continued
('Dragon Lightning', 'Seeking dragon-shaped lightning bolt', 5, FALSE, 250, 2, 120, NULL, 180, 'level*6', 0, NULL, 'shocked', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Raise Dead', 'Resurrects target with level/vitality loss', 5, FALSE, 280, 5, 5, NULL, 0, NULL, 0, NULL, 'resurrection', 'permanent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sand Field: All', 'Immobilizing sandstorm', 5, FALSE, 250, 2, 100, 50, 0, NULL, 0, NULL, 'multiple_debuff', '1 minute', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 5th', 'Single tier 5 angel Guardian summon, or multiple tier 4 angels', 4, FALSE, 270, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 5th', 'Single tier 5 beasts Guardian summon, or multiple tier 4 beasts', 4, FALSE, 270, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
('Summon Undead 5th', 'Single tier 5 undead Guardian summon, or multiple tier 4 undead', 5, FALSE, 270, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Teleportation', 'Long-range teleport', 5, FALSE, 200, 2, -1, NULL, 0, NULL, 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vermin Bane', 'Anti-insect white mist', 5, FALSE, 230, 2, 60, 30, 150, 'level*6', 0, NULL, 'insect_bane', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Undying Flame', 'Negative energy flames', 5, FALSE, 240, 1, 0, NULL, 0, NULL, 0, NULL, 'undying_flames', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 6 (300-400 MP)
('Control Weather', 'Weather manipulation', 6, FALSE, 350, 5, 26400, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Heal', 'Major heal and cure', 6, FALSE, 300, 2, 5, NULL, 0, NULL, 200, 'level*7', 'cure_status', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Flamewing', 'Flame wing creation', 6, FALSE, 320, 2, 0, NULL, 0, NULL, 0, NULL, 'flame_wings', '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Locate Object', 'Object finding', 6, FALSE, 300, 3, 5280, NULL, 0, NULL, 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Obey', 'Controls lower rank undead', 6, FALSE, 320, 2, 60, NULL, 0, NULL, 0, NULL, 'undead_control', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 6th', 'Single tier 6 angel Guardian summon, or multiple tier 5 angels', 4, FALSE, 350, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 6th', 'Single tier 6 beasts Guardian summon, or multiple tier 5 beasts', 4, FALSE, 350, 2, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
('Summon Undead 6th', 'Single tier 6 undead Guardian summon, or multiple tier 5 undead', 6, FALSE, 350, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wall of Hell', 'Hellfire barrier', 6, FALSE, 350, 2, 120, NULL, 200, 'level*7', 0, NULL, 'hellfire', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 7 (400-500 MP)
('Blasphemy', 'Unholy damage burst', 7, FALSE, 450, 2, 100, 30, 300, 'level*8', 0, NULL, 'unholy_damage', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chain Dragon Lightning', 'Multi-target dragon lightning', 7, FALSE, 480, 3, 150, 40, 320, 'level*8', 0, NULL, 'chain_shock', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create Greater Item', 'Creates high-tier items and equipment', 7, FALSE, 450, 3, 5, NULL, 0, NULL, 0, NULL, NULL, 'permanent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Focus Magic', 'Magic enhancement', 7, FALSE, 400, 2, 5, NULL, 0, NULL, 0, NULL, 'magic_boost', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Greater Teleportation', 'Unlimited teleport', 7, FALSE, 450, 2, -1, NULL, 0, NULL, 0, NULL, NULL, 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Greater Word of Curse', 'Close-range curse attack', 7, FALSE, 420, 2, 5, NULL, 280, 'level*8', 0, NULL, 'cursed', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hell Flame', 'Black flame burst', 7, FALSE, 460, 2, 90, 15, 350, 'level*8', 0, NULL, 'hellfire', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hellfire Wall', 'Soul-burning wall', 7, FALSE, 470, 3, 100, NULL, 0, NULL, 0, NULL, 'soul_burn', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Holy Smite', 'Column of holy light punishing evil', 7, FALSE, 450, 2, 90, 15, 350, 'karma*8', 0, NULL, 'holy_damage', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Napalm', 'Intense flame column', 7, FALSE, 450, 2, 120, 20, 340, 'level*8', 0, NULL, 'burning', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Angelic Army', 'Summons many low-tier angels', 7, FALSE, 480, 4, 100, 50, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Phoenix Flame', 'Self-resurrection with flame damage', 7, FALSE, 480, 3, 0, 15, 100, 'level*4', 0, NULL, 'resurrection', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Resurrection', 'Powerful revival spell', 7, FALSE, 450, 4, 5, NULL, 0, NULL, 0, NULL, 'resurrection', 'permanent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shining Burst', 'Karma-based holy area damage', 7, FALSE, 450, 2, 90, 30, 300, 'karma*8', 0, NULL, 'holy_damage', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 7th', 'Single tier 7 angel Guardian summon, or multiple tier 6 angels', 7, FALSE, 450, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Demon 7th', 'Single tier 7 demon Guardian summon, or multiple tier 6 demons', 7, FALSE, 450, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 7th', 'Single tier 7 beast Guardian summon, or multiple tier 6 beasts', 7, FALSE, 450, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Undeath Army', 'Summons many low-tier demons', 7, FALSE, 480, 4, 100, 50, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 8 (500-600 MP)
('Aspect of Elemental', 'Elemental resistance', 8, FALSE, 500, 3, 0, NULL, 0, NULL, 0, NULL, 'elemental_aspect', '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Astral Smite', 'Anti-ethereal damage', 8, FALSE, 520, 2, 60, NULL, 400, 'level*9', 0, NULL, 'astral_damage', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Death', 'Instant death', 8, FALSE, 600, 3, 60, NULL, 1000, NULL, 0, NULL, 'death', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dimensional Lock', 'Anti-teleport field', 8, FALSE, 550, 3, 100, 50, 0, NULL, 0, NULL, 'teleport_lock', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Distort Moral', 'Corrupts target''s morality', 8, FALSE, 500, 3, 30, NULL, 0, NULL, 0, NULL, 'morality_shift', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energy Drain', 'Level drain', 8, FALSE, 580, 2, 5, NULL, 0, NULL, 0, NULL, 'level_drain', 'permanent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Explosion', 'Massive force burst', 8, FALSE, 540, 2, 120, 40, 450, 'level*9', 0, NULL, 'knockback', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Insanity', 'Induces madness in target', 8, FALSE, 520, 2, 60, NULL, 0, NULL, 0, NULL, 'insanity', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Planar Eye', 'Long-range surveillance', 8, FALSE, 500, 5, -1, NULL, 0, NULL, 0, NULL, 'scrying', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Remote Viewing', 'Long-range vision', 8, FALSE, 500, 5, 5280, NULL, 0, NULL, 0, NULL, NULL, '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Undead 8th', 'Summons mid-tier undead', 6, FALSE, 650, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 8th', 'Summons mid-tier beast', 6, FALSE, 650, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 8th', 'Summons mid-tier angel', 6, FALSE, 650, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wave of Pain', 'Causes overwhelming agony', 8, FALSE, 550, 2, 60, 30, 400, 'level*9', 0, NULL, 'pain', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 9 (600-800 MP)
('Bless of Titania', 'Fairy guide summon', 9, FALSE, 650, 3, 0, NULL, 0, NULL, 0, NULL, 'fairy_guide', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Call Greater Thunder', 'Supreme lightning', 9, FALSE, 700, 3, 200, NULL, 500, 'level*10', 0, NULL, 'greater_shock', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Crack in the Ground', 'Creates entangling fissure', 9, FALSE, 650, 3, 90, 30, 450, 'level*10', 0, NULL, 'entangled', '1 minute', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Elemental Form', 'Transforms into elemental', 9, FALSE, 700, 3, 0, NULL, 0, NULL, 0, NULL, 'elemental_form', '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('God''s Eye', 'Advanced invisible scrying', 9, FALSE, 650, 3, -1, NULL, 0, NULL, 0, NULL, 'true_sight', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Grasp Heart', 'Instant death by heart crush. If resisted, stuns the target', 9, FALSE, 750, 2, 60, NULL, 1000, NULL, 0, NULL, 'death', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Greater Rejection', 'Cancels greater summoning', 9, FALSE, 700, 2, 60, NULL, 0, NULL, 0, NULL, 'summon_cancel', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lead of Yatagarasu', 'Three-legged crow guide', 9, FALSE, 650, 3, -1, NULL, 0, NULL, 0, NULL, 'pathfinding', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nuclear Blast', 'Devastating explosion', 9, FALSE, 750, 4, 300, 50, 550, 'level*10', 0, NULL, 'multiple_status', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Perfect Unknowable', 'Perfect stealth', 9, FALSE, 700, 3, 0, NULL, 0, NULL, 0, NULL, 'perfect_stealth', '30 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Polar Claw', 'Powerful ice claw attack', 9, FALSE, 700, 2, 60, NULL, 500, 'level*10', 0, NULL, 'frozen', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tempest', 'Creates destructive storm', 9, FALSE, 750, 4, 300, 100, 400, 'level*10', 0, NULL, 'storm_effects', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Undead 9th', 'Summons high-tier undead', 6, FALSE, 750, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 9th', 'Summons high-tier beast', 6, FALSE, 750, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 9th', 'Summons high-tier angel', 6, FALSE, 750, 3, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Temporal Stasis', 'Time-freezes single target, preventing actoins and taking damage', 9, FALSE, 750, 3, 60, NULL, 0, NULL, 0, NULL, 'time_stop', '1 minute', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('True Death', 'Permanent death', 9, FALSE, 800, 4, 60, NULL, 1000, NULL, 0, NULL, 'true_death', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('True Resurrection', 'Perfect resurrection', 9, FALSE, 750, 5, 5, NULL, 0, NULL, 0, NULL, 'true_resurrection', 'permanent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vermilion Nova', 'Supreme fire pillar', 9, FALSE, 700, 3, 120, 30, 500, 'level*10', 0, NULL, 'incineration', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Tier 10 (800-1000 MP)
('Armageddon - Evil', 'Demon army summon', 10, FALSE, 850, 5, 300, 100, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Armageddon - Good', 'Angel army summoning', 10, FALSE, 850, 5, 300, 100, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Body of Effulgent Beryl', 'Anti-bludgeon shield', 10, FALSE, 800, 3, 0, NULL, 0, NULL, 0, NULL, 'bludgeon_immune', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Body of Effulgent Aquamarine', 'Pierce damage immunity', 10, FALSE, 800, 3, 0, NULL, 0, NULL, 0, NULL, 'pierce_immune', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Body of Effulgent Heliodor', 'Slash damage immunity', 10, FALSE, 800, 3, 0, NULL, 0, NULL, 0, NULL, 'slash_immune', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Control Amnesia', 'Memory manipulation', 10, FALSE, 900, 5, 5, NULL, 0, NULL, 0, NULL, 'memory_control', 'permanent', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Create Fortress', 'Summoned fortress', 10, FALSE, 850, 10, 60, NULL, 0, NULL, 0, NULL, NULL, '24 hours', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Field of Unclean', 'Creates corrupted area', 10, FALSE, 850, 4, 100, 50, 600, 'level*12', 0, NULL, 'corruption', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Implosion', 'Causes target to collapse', 10, FALSE, 900, 3, 60, NULL, 800, 'level*12', 0, NULL, 'implode', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mercy of Shorea Robusta', 'Druid resurrection protection', 10, FALSE, 950, 3, 0, NULL, 0, NULL, 100, 'level*10', 'death_protection', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mirror World', 'Creates reflective barrier dome', 10, FALSE, 900, 3, 0, 100, 0, NULL, 0, NULL, 'reflection', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mist of Super Acid', 'Extreme acid damage field', 10, FALSE, 900, 3, 0, 60, 750, 'level*12', 0, NULL, 'super_acid', '1 minute', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Meteor Fall', 'Summons devastating meteor', 10, FALSE, 950, 4, 300, 100, 850, 'level*12', 0, NULL, 'meteor_impact', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nature''s Shelter', 'Creates divine bunker', 10, FALSE, 850, 4, 60, 30, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Reality Slash', 'Space-cutting attack', 10, FALSE, 950, 3, 60, NULL, 800, 'level*12', 0, NULL, 'reality_cut', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Seven Trumpeter', 'Divine judgment call', 10, FALSE, 900, 4, 300, 100, 800, 'level*12', 0, NULL, 'divine_judgment', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Stream of Lava', 'Continuous lava damage', 10, FALSE, 850, 3, 90, 30, 700, 'level*12', 0, NULL, 'melting', '1 minute', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Angel 10th', 'Summons high-tier angel', 10, FALSE, 900, 4, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Monster 10th', 'Summons high-tier monster', 10, FALSE, 900, 4, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Summon Undead 10th', 'Summons high-tier undead', 10, FALSE, 900, 4, 30, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
('Time Stop', 'Time freeze', 10, FALSE, 1000, 3, 0, 50, 0, NULL, 0, NULL, 'time_stop', '3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ultimate Disturb', 'Magic resistance boost', 10, FALSE, 800, 2, 5, NULL, 0, NULL, 0, NULL, 'magic_resist_up', '10 minutes', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Uriel', 'Karma-based holy damage', 10, FALSE, 850, 3, 60, NULL, 800, 'karma*15', 0, NULL, 'holy_judgment', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Super Tier (1000+ MP)
('Fallen Down', 'Divine punishment', 11, TRUE, 1200, 10, 5280, 100, 2000, 'level*15', 0, NULL, 'divine_judgment', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Wish Upon A Star', 'Reality alteration', 11, TRUE, 1500, 10, -1, NULL, 0, NULL, 0, NULL, 'wish_effect', 'varies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pantheon', 'Angel army summon', 11, TRUE, 1300, 10, 100, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Stampede', 'Beast army summon', 11, TRUE, 1300, 10, 100, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pandemonium', 'Demon army summon', 11, TRUE, 1300, 10, 100, NULL, 0, NULL, 0, NULL, NULL, '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ia Shub-Niggurath', 'Dark Young summoning', 11, TRUE, 1400, 10, 5280, 200, 2500, 'level*15', 0, NULL, 'sacrifice', '1 hour', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Metamagic Spells
('Boost Magic', 'Elevates spell tier and power', 0, FALSE, 50, 1, 0, NULL, 0, 'original*1.5', 0, NULL, 'boosted', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Delay Magic', 'Delays spell activation', 0, FALSE, 30, 1, 0, NULL, 0, NULL, 0, NULL, 'delayed', 'varies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Extend Magic', 'Extends spell duration', 0, FALSE, 40, 1, 0, NULL, 0, NULL, 0, NULL, 'extended', 'varies', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Maximize Magic', 'Maximizes spell damage', 0, FALSE, 60, 1, 0, NULL, 0, 'max_damage', 0, NULL, 'maximized', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Over Magic', 'Casts higher tier spell', 0, FALSE, 100, 2, 0, NULL, 0, 'tier_up', 0, NULL, 'enhanced', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Penetrate Magic', 'Increases magic penetration', 0, FALSE, 45, 1, 0, NULL, 0, NULL, 0, NULL, 'penetrating', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Silent Magic', 'Removes verbal components', 0, FALSE, 35, 1, 0, NULL, 0, NULL, 0, NULL, 'silenced', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Twin Magic', 'Creates two spell effects', 0, FALSE, 75, 1, 0, NULL, 0, 'original*2', 0, NULL, 'twinned', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Triplet Magic', 'Creates three spell effects', 0, FALSE, 100, 2, 0, NULL, 0, 'original*3', 0, NULL, 'tripled', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Widen Magic', 'Increases spell range/area', 0, FALSE, 50, 1, 0, NULL, 0, NULL, 0, NULL, 'widened', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Five Elements Yin', 'Yin principle enhancement', 0, FALSE, 80, 2, 0, NULL, 0, 'yin_enhanced', 0, NULL, 'yin', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Five Elements Yang', 'Yang principle enhancement', 0, FALSE, 80, 2, 0, NULL, 0, 'yang_enhanced', 0, NULL, 'yang', 'instant', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);